baseURL: https://rodriguezoma-website.netlify.app/
languageCode: en-us
title: ZOMA W Rodrigue
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Start
    subtitle: |-
      this is my first portflio website
    title: Wendyam Rodrigue ZOMA
  blog: {}
  contact:
    address:
      - city: Koudougou, secteur N 07
        country: Burkina Faso
        street: Rue 00024
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wrodriguezoma@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+226) 62 46 59 19 / 76 52 96 98
        title: Phone
        
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: wendyamrodriguezoma
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/@rodrigue_zoma
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/wendyamrodriguezoma
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/rodrigo_zoma
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/rodriguezoma
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/feed/?trk=404_page
  image: ''
  name: ZOMA W Rodrigue
  navigation:
    button1:
      - name: Start
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: imag1.JPG
        subtitle: Ipsum Dolor Sit Amet
        title: Aliquam
        url: blogs/aliquam
      - image: imag3.JPG
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: imag8.JPG
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: imag11.JPG
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: imag7.JPG
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: imag9.JPG
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: ok
    enable: yes
    subtitle: "My name is Wendyam Rodrigue ZOMA, I was born on February 24, 1996 and I am originally from the Central West region, particularly in Koudougou. I am currently in a year of license in an institute of technology, I like my studies, it is quite diversified, dynamic, clearly I like what I do, yet there is a field that I like very much which networking!

Since I was little, I have a taste for travelling!
For a long time, I spent my vacations in Bobo Dioulasso and Banfora. Banfora was a region that I fell in love with thanks to its beauty, its nature and the serenity that it brings me. 
Then, I discovered the Ivory Coast thanks to a "free" religious trip! It is a country that fascinates me with many facets, an important cultural activity and very nice people! I love the city of Koudougou, it is my city, my favorite, it is a city where I feel good, where there is brotherhood!

Translated with www.DeepL.com/Translator (free version)."
    title:  libero
    url: blogs
